### ISSUE TITLE
.MTL Files Support?

### ISSUE THREAD

**Issue by brondbjerg** [neverhood311/Stop-motion-OBJ#10]
Hi,
Thanks for a great script... it works really well!
I have one issue, and perhaps it's how I'm generating my OBJ & MTL files?
When I import a sequence of OBJ files the geometry comes into Blender perfectrly, but the MTL files seem to be ignored. They are all named the same as the OBJ files?

Should this work with your script? Could it be added if not?
Any thoughts on dojng this would be great!
Thanks again!

Mike

**Comment by neverhood311** [comment]
Hey Mike,

Double-checking the code, I confirmed that the add-on as it stands doesn't do anything special to handle MTL files. My use-case was to import a sequence of OBJs (all without UVs), then create a Cycles shader from scratch. Didn't even think about MTLs.

Unfortunately, you've caught me during the tail end of a really busy semester, but I might have time to work on this in January. Or you're welcome to take a crack at it if you want.

**Comment by brondbjerg** [comment]
OK, great! Thanks! 
I'll certainly have a dig in and see if I can have a go (don't hold out much hope though ;).
If you magically find some time, that would be great!
Thanks again for the add-on so far.. it's great!
M

**Comment by brondbjerg** [comment]
Hi Justin, just wanted to follow up on this. I didn't get anywhere with it myself (limited Python skills) but is it something might consider doing? I may have some limited budget if that helps find you some time? Thanks!

**Comment by neverhood311** [comment]
Hey Mike,

I'll look into this. Would you be able to send me a small set of OBJs and MTLs to test with? At least 4 or 5? That would be really helpful. A Dropbox link if you can.

Thanks

**Comment by brondbjerg** [comment]
Great! I will dig out the files I was testing with before, let me sort something out this weekend! Can you get in touch via mike [at] kultur [dot] design 
thanks!

**Comment by neverhood311** [comment]
I figured out how to bring in multiple MTL files. I'm thinking of adding a checkbox to the sequence to enable/disable multiple materials (my main use-case is to use a single material that is shared by all of the meshes, so I want to have the option to switch between the two modes).

What should I call the checkbox? I was thinking something like "Per-frame Material" or "One Material per Frame" or "Material Per Frame" or "Dynamic Material". Do you like any of these? Or can you think of a better and/or shorter name that still suggests the meaning of the checkbox?

**Comment by neverhood311** [comment]
Give this branch a try and see if it works for you:
[https://github.com/neverhood311/Stop-motion-OBJ/tree/multiple-materials](https://github.com/neverhood311/Stop-motion-OBJ/tree/multiple-materials)

**Comment by brondbjerg** [comment]
Hi Justin, just gave it a try on both a simple a sequence, and a more complex (30 frames, each frame OBJ: ~400KB, MTL: ~ 120KB). the simple import was pretty quick, but the more complex set took a while.

But... after 10 mins, it did get there and the animation seems perfect... I'll do some more rigorous testing, but it seems great!

**Comment by neverhood311** [comment]
Glad to hear it. I'll do more testing, too. My guess as to why it's taking so long is because you have a different material for each face of each mesh. Blender has to create all of these materials and assign them to each object. I'm guessing it's not optimized for this use-case. (I wonder what the Blender developers would say if we told them to speed this up).

I'm interested to know what you think about using this feature. Do you think a checkbox to switch modes is the right idea? And what about the name?

**Comment by brondbjerg** [comment]
I guess as long as it doesn't crash we can live with it taking a while!

The feature is great, checkbox makes sense, but wonder if un-checked by default would be better for most user's needs?
