### ISSUE TITLE
No Matching Files found

### ISSUE THREAD

**Issue by ke10g** [neverhood311/Stop-motion-OBJ#108]
Hi. I'm trying to import an object sequence made with Depthkit using azure kinect. I'm on Blender 2.91.0 using stop-motion-obj 2.1.0. 

On import, I navigate to the folder where the Depthkit export is: it is filled with commonly prefixed .obj, .mtl, and .png files (Blender doesn't see the latter), one each for each frame. I copy the prefix (everything before the frame number), and enter it as the file name in the Blender import pane. 

I get an error: No Matching Files Found. 

What am I doing wrong?

**Comment by neverhood311** [comment]
Try downloading one of the [Sample Sequences](https://github.com/neverhood311/Stop-motion-OBJ/tree/master/examples) from the repo. Are you able to import those sequences successfully?

If those are working, would it be possible to share a few frames (2 or 3) of your sequence so I can debug on my end? Or at the very least, take a screenshot of the Import Mesh Sequence window just before you click Select Folder to import the files?

**Comment by mfogelson** [comment]
Check in the top right corner to select the correct file type. 

Simple problem I realized after seeing this post

**Comment by jessiez0810** [comment]
I'm having the same problem with a sequence of .ply files and the file type is set to the correct one. It still gives me the no matching files found problem. I wonder why?

**Comment by neverhood311** [comment]
@jessiez0810 Which version of Blender and which version of the addon?
Also, are you able to share 2 or 3 of your meshes?

**Comment by jessiez0810** [comment]
@neverhood311 I am using blender 2.93 and here is a sample folder for you to test https://drive.google.com/file/d/1kaGNoscB8uwuMJ5_43ldUP_erIM-IGcm/view?usp=sharing

**Comment by neverhood311** [comment]
So it looks like the files have no real filename prefix; they're just numbers like "00001.ply", "00002.ply", etc.
What are you entering as the File Name Prefix when you try to import the sequence?

**Comment by jessiez0810** [comment]
Hello, you are right about the filename prefix. I use a volumetric video recording software and the recorded.ply files from that software don't have a filename prefix. When I manually give the files a prefix like in the picture below, it worked! 
<img width="1213" alt="Screen Shot 2021-06-08 at 4 06 12 PM" src="https://user-images.githubusercontent.com/56314473/121250465-bd709b80-c873-11eb-8dfd-234b95138e5a.png">

**Comment by gokcergun** [comment]
Hi, 

I'm having the same problem while trying to open .obj sequence. (Error: No mathing files found)
I tried it with Blender 3.1.2 and 2.9.1. Both versoins give the same error. 
I can open the obj files separately via import/wavefront (.obj).
I downloaded your example sequence to test it. I got the same error. 
OS: Windows 11

Thanks for your help in advance
