### ISSUE TITLE
Set Object Origin for every frame in sequence?

### ISSUE THREAD

**Issue by WillemKauf** [neverhood311/Stop-motion-OBJ#122]
Hi,

I am running into the painful issue of having to go frame by frame to set the object origin for every entry in the sequence. Otherwise, my imported sequence keeps changing positions frame to frame. Is this an issue on my end, or something people know how to deal with?

**Comment by enzyme69** [comment]
Can't you select all objects and then set origin to 3D cursor?

**Comment by neverhood311** [comment]
Or you could just make an empty object and put the whole sequence as a child of the empty. Then just move the empty around.

**Comment by WillemKauf** [comment]
Yeah, that's what I ended up doing. Thanks!

**Comment by StephenMcAvoy** [comment]
Hi Willem,
What program are you using to generate your meshes?
Programs that can use MoCap files rely on the mesh displacement from the origin to position it in the World Space. I use Poser for generating meshes and to remove the displacement before exporting is easy. There might be an option to export the sequence with “no world transformations” or something like that.
