### ISSUE TITLE
Exporting to Alembic animation put all meshes into the same frame

### ISSUE THREAD

**Issue by EgeDogan** [neverhood311/Stop-motion-OBJ#127]
**System Information**
Operating system: Windows 10

**Addon version**
Broken: (example: 2.0.2)
Worked:

**Describe the bug**
When exporting to alembic, blender puts every geometry into the first frame, making it unsuable as an animation.

**Steps To Reproduce**
Either bake the geometries or do not, export as alembic.

Thanks in advance.

**Comment by neverhood311** [comment]
Sequence export is not officially supported, but see the workaround in #46
