### ISSUE TITLE
textures are not assigned

### ISSUE THREAD

**Issue by beatfoot** [neverhood311/Stop-motion-OBJ#128]
hi! we love this! we imported a sequence that has 600 OBJ with 600 MTL and 600 PNG.
we checked the box under Material per Frame
the sequence works great BUT the textures are not assigned at all! 
all we get is a white textured sequence

is there any thing we are missing here?

**Comment by neverhood311** [comment]
Hey, really sorry, but I'm in the middle of moving cross-country, so I
won't be able to look into this for at least a week.
If you send a sample of the sequence (maybe the first 3 frames or so), I
can take a look when I have time.

**Comment by beatfoot** [comment]
hi justin
good luck with your moving !
wishing you all the best

heres the 3 first frames:
https://drive.google.com/drive/folders/1tMASwHwR-f175j57-InB2ah-ytwVGZjG?usp=sharing

thanks so much

**Comment by StephenMcAvoy** [comment]
Hi beatfoot
I took a look at your  MTL files and they look quite empty. They should look something like:

newmtl Preview:1
Ns 59.9999
Ka 0 0 0
Kd 0.221809 0.626301 0.560808
Ks 0.170806 0.112516 0.107382
d 1
newmtl Trunk:1
Ns 4
Ka 0.0147059 0.0147059 0.0147059
Kd 1 1 1
Ks 0.0588235 0.0588235 0.0588235
map_Kd F:\Graphics\Poser Libraries\Miscellaneous\Runtime\Textures\Mapps_Tex\HoSM\Plants\OT_Shrub_Bark.jpg
d 1
newmtl Branch:1
Ns 4
Ka 0.0147059 0.0147059 0.0147059
Kd 1 1 1
Ks 0.0588235 0.0588235 0.0588235
map_Kd F:\Graphics\Poser Libraries\Miscellaneous\Runtime\Textures\Mapps_Tex\HoSM\Plants\OT_Shrub_Bark.jpg
d 1

Your obj files load without textures using the standard importer as well

**Comment by beatfoot** [comment]
oh yeah !
thanks so much!
we've managed to put in another sequence that does work !
thank you for everything

**Comment by StephenMcAvoy** [comment]
Pleased to have helped. :-D
