### ISSUE TITLE
I can't see the installed addon

### ISSUE THREAD

**Issue by LensNinja-Aleksa** [neverhood311/Stop-motion-OBJ#131]
Hello,
I tried to install the addons via Preferences>AddOns and via Blender>2.93>scripts>addons and still can't see them in the AddOn section to switch them on. All three Official/Community/Testing view options are enabled too. 
Please, could you advise me of the solution?

**Comment by neverhood311** [comment]
@LensNinja-Aleksa Why did you close this issue? Were you able to resolve the issue?

**Comment by LensNinja-Aleksa** [comment]
Yes I did resolve the issue. 😌
