### ISSUE TITLE
Import multiple mesh sequences

### ISSUE THREAD

**Issue by Roibabouin** [neverhood311/Stop-motion-OBJ#134]
Hello,

For some reasons, I sometime need to import 5-10 mesh sequences.

Would it be possible to upgrade the menu to add multiple mesh sequences at once ? 
Maybe multiples input-boxes we would loop on ?

Regards, 

Thomas.

**Comment by neverhood311** [comment]
Hi Thomas,

This would be a nice addition, but to be completely honest, I don't see this feature being added. As it stands, I didn't write the code for the menu UI completely, I'm just piggybacking on the existing File Finder UI code. To create a full multi-sequence import UI from scratch would be more work than I'm able to put into it.

I'll make a note in the backlog so this idea isn't lost, though.
