### ISSUE TITLE
Ability to reload meshes

### ISSUE THREAD

**Issue by breannansmith** [neverhood311/Stop-motion-OBJ#14]
It would be great to be able to reload cached meshes if the original files are changed on disk! This functionality is available in the similar file node in Houdini, and it makes interfacing with external sources so much easier.

**Comment by neverhood311** [comment]
FYI, I'm currently working on adding this feature to the 2.80 branch. See the progress here: [https://github.com/neverhood311/Stop-motion-OBJ/tree/feature/reload-from-disk](https://github.com/neverhood311/Stop-motion-OBJ/tree/feature/reload-from-disk)

**Comment by neverhood311** [comment]
@breannansmith When you have a minute, could you test out this new feature? I added a button called "Reload From Disk". It shows up in between Playback Speed and Shading. Seems to be working for me, but I could use another set of eyes. You can get the script here: [https://github.com/neverhood311/Stop-motion-OBJ/blob/feature/reload-from-disk/stop_motion_obj.py](https://github.com/neverhood311/Stop-motion-OBJ/blob/feature/reload-from-disk/stop_motion_obj.py)

**Comment by neverhood311** [comment]
I went ahead and merged this into the 2.80 branch. See [https://github.com/neverhood311/Stop-motion-OBJ/pull/16](https://github.com/neverhood311/Stop-motion-OBJ/pull/16)

**Comment by breannansmith** [comment]
Somehow I missed this commit, it is working great, thanks for implementing this! 🥳
