### ISSUE TITLE
No Matching Files found

### ISSUE THREAD

**Issue by gokcergun** [neverhood311/Stop-motion-OBJ#156]
Operating system: Windows 10
Blender version: Blender 3.1.2 (also tried 2.9.1)
Addon version: latest version of Stop Motion OBJ

Hi, 

When I try to open .obj sequence. I am getting No mathcing objects found error. Tried both Blender 3.1.2 and 2.9.1, got same error. 
I renamed the obj files as frame_0.obj, frame_1.obj etc. 
I can open the obj files separately via import/wavefront (.obj).
I tested it also with  your example sequence (horse_gallob), I got the same error.

I opened the topic as a new issue because none of the solutions that were suggested at previous issues solved my problem. 

Thanks for your help in advance

**Comment by neverhood311** [comment]
Hi @gokcergun, a few questions:

1. Which version of the addon are you using? (for example, is it 2.1.1 or is it a 2.2.0-alpha version?)
2. Can you send me a screenshot of Blender just before you're about to click 'Select Folder' to import the sequence?

**Comment by gokcergun** [comment]
Wow, yes, it works now. I was not aware that file name should be the same of name prefix. Thank you.
