### ISSUE TITLE
export this reBuild-animation?

### ISSUE THREAD

**Issue by SmellyTrotter** [neverhood311/Stop-motion-OBJ#163]
the animation reBuild by Stop Motion OBJ can be export to be a FBX or others? 
I found that the exported object doesn't have animation, did I set it up wrong?
thank you

**Comment by neverhood311** [comment]
Stop Motion OBJ doesn't officially support sequence exporting. See https://github.com/neverhood311/Stop-motion-OBJ/wiki#troubleshooting I've mentioned FBX and Alembic there
