### ISSUE TITLE
PLY Import Broken on Blender 2.8

### ISSUE THREAD

**Issue by bkreimer** [neverhood311/Stop-motion-OBJ#18]
This is a great tool! It works for me on 2.79, but the version of the code for 2.8 gives me an error when I try to import PLY files in Blender 2.8 (I can import OBJ sequences without issue though). Only the first PLY in the  folder sequence gets imported. The same PLY sequence imports fine into 2.79.

Here's the error I'm getting in 2.8 when importing my PLYs:

F:\Test PLY\Normals\e*.ply
['F:\\Test PLY\\Normals\\e_001.ply', 'F:\\Test PLY\\Normals\\e_002.ply', 'F:\\Test PLY\\Normals\\e_003.ply']

Successfully imported 'F:\\Test PLY\\Normals\\e_001.ply' in 55.074 sec
Info: Deleted 1 object(s)
Traceback (most recent call last):
  File "C:\Users\Ben Kreimer\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\stop_motion_obj.py", line 547, in execute
    num = MSC.loadSequenceFromFile(obj, dirPath, fileName)
  File "C:\Users\Ben Kreimer\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\stop_motion_obj.py", line 226, in loadSequenceFromFile
    _obj.mesh_sequence_settings.meshNames += tmpMesh.name + '/'
ReferenceError: StructRNA of type Object has been removed

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by neverhood311** [comment]
Thanks for reporting this!

I noticed from your error log that e_001.ply took 55 seconds to load. That’s ridiculously long. Is it a really complex mesh? If so, do you have a simpler mesh you could try? I’ll see what I can learn on my end.

**Comment by neverhood311** [comment]
Fixed this in PR[https://github.com/neverhood311/Stop-motion-OBJ/pull/19](https://github.com/neverhood311/Stop-motion-OBJ/pull/19)
Apparently there's a minor discrepancy between the OBJ, STL, and PLY importers that was introduced in Blender 2.80. I've now accounted for it.
