### ISSUE TITLE
im a studen. when i did my homework, i faced on a trouble. please help me! that‘s scary that i will "reply" my semester 

### ISSUE THREAD

**Issue by MYuu0226** [neverhood311/Stop-motion-OBJ#181]
**System Information**
Operating system:

**Addon  @version**
Broken: 2.1.0
Worked: blender 4.0

**Describe the bug**
error when I import obj, I'm sorry I don't know anything

**Comment by MYuu0226** [comment]
![Uploading dac985d0101e311108f87c94db6c09e.png…]()

**Comment by neverhood311** [comment]
Not enough information

**Comment by MYuu0226** [comment]
idk how to upload my picture

**Comment by MYuu0226** [comment]
![Uploading dac985d0101e311108f87c94db6c09e.png…]()

**Comment by neverhood311** [comment]
Stop Motion OBJ doesn't work for Blender 4.0 yet. Try Blender 3.6 instead

**Comment by MYuu0226** [comment]
Python: Traceback (most recent call last):
File "C:\Users\**\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-0BJ\panels,py", line 204, in executemeshCount = loadSequenceFromMeshFiles(seqObj, mss.dirPath, mss.fileName)
File "C:\Users\**\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Stop-motion-0BJ\panels,py", line 493, in loadSecuenceFromMeshFlesmss.fileImporter.load(mss.fileFormat, file)


and so on

**Comment by MYuu0226** [comment]
AttributeError: Calling operator "bpy.ops.import_scene.obj" error, could not be found

**Comment by MYuu0226** [comment]
I was pleasantly surprised by the speed of your response, and I appreciate it

**Comment by MYuu0226** [comment]
im succeed! Blender 3.6 is right! Thank you! This is the first time I have asked for help from foreigners on the Internet, I didn't expect it to be so successful, it's such a wonderful thing, I'm grateful! Bless you!
