### ISSUE TITLE
Import multiple PLY file meet AttributeError: Calling operator "bpy.ops.import_mesh.ply" error, could not be found

### ISSUE THREAD

**Issue by snowmint** [neverhood311/Stop-motion-OBJ#183]
**System Information**
Operating system: Ubuntu22.04

**Addon version**
Broken: 2.2.1 and 2.2.0.beta

**Describe the bug**
When I try to import a PLY mesh sequence, I receive the following console errors:
```
Report: Error
Python: Traceback (most recent call last):
File "/home/mtl/.config/blender/4.0/scripts/addons/Stop-motion-OBJ/[panels.py](https://panels.py/)", line 300, in execute
operator = sfile.active_operator
File "/home/mtl/.config/blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 786, in loadSequenceFromMeshFiles 
#grab the current mesh so we can put it back later
File "/home/mtl/.config/blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 419, in load emptyMeshNameElement.key = theMesh.name
File "/home/mtl/.config/blender/4.0/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 484, in loadPLY
numFrames = 0
File "/opt/blender/4.0/scripts/modules/bpy/ops.py", line 109, in_call
ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.import_mesh.ply" error, could not be found
```
Total have 4617 files, I tried to use partial of it, but still meet the same error.

**Steps To Reproduce**
1. Go to File > Import > Mesh Sequence
2. Change 'file type' to 'PLY'
3. Type first few letters of the PLY sequence filenames.
4. Click 'Select Folder'
5. Receive console errors.

**Expected behavior**
The PLY sequence should import and be playable from the timeline.

**Screenshots**
![Screenshot from 2023-12-05 15-46-28](https://github.com/neverhood311/Stop-motion-OBJ/assets/7868828/b48962ae-3d94-4c51-87cd-85e126a22852)
![Screenshot from 2023-12-05 15-46-28](https://github.com/neverhood311/Stop-motion-OBJ/assets/7868828/1ce61668-f51f-46d9-96f5-2d94ca5725e0)

**Comment by snowmint** [comment]
Few of my PLY file uploaded on Google drive, I want it play in 40fps:
https://drive.google.com/drive/folders/158bU6td3DIzB-uiuVfXwszUJdHstwW7n?usp=sharing

**Comment by neverhood311** [comment]
Blender 4.0 removed the old python-based PLY importer. You'll need to use Blender 3.6 or earlier until I refactor the addon for Blender 4.0.
