### ISSUE TITLE
v2.2.0 doesn't work with Blender 4.2

### ISSUE THREAD

**Issue by Basic0** [neverhood311/Stop-motion-OBJ#191]
**System Information**
OS: Windows 11, Blender 4.2

**Addon version**
Broken: 2.2.0/Latest

**Describe the bug**
After selecting a mesh sequence to import (and entering the filename to match), clicking add folder does nothing.

**Steps To Reproduce**
1. Follow steps in Quick Start Tutorial in the readme for the correct version ("Blender 2.92+")

That's a little frustrating but hey ... Open Source, so I would normally just shrug and move on but... You're explicitly directing people to itch.io for a paid download with minimum pricing set.

Not being familiar with Blender plugins, I had a quick hunt for any obvious build process and -failing to find one- stumped up.

Imagine my irritation at finding what I've paid for is a zip file of a folder in the repository.

That's deceptive at best, but I was willing to take it as a learning experience right up until the point I found out that it doesn't actually work.

At the **very least**, you should update your documentation to highlight that this project is broken and not fit for purpose.

If there's a reason I shouldn't report this as a scam to itch.io, please do let me know.

**Comment by neverhood311** [comment]
I'm sorry for the confusion. Stop Motion OBJ v2.2.0 is compatible with Blender versions 2.92-3.6.x. It will not work with version 4.0 or later. I've stated this in the release notes:
![image](https://github.com/user-attachments/assets/e30e3740-1a04-4084-8ec0-74e97ebee42f)
I've also stated this in the description on itch.io:
![image](https://github.com/user-attachments/assets/ae798f3e-1cde-407f-8e13-06b674df9008)

To be fair, I could have made these compatibility notes even more obvious (which I will go and do now), however I never intended to trick people into buying something that wouldn't work for them.

If you'd like a refund, I'd be happy to make that happen. Just email me and we'll figure it out.

As for your other concerns, please open a new [discussion](https://github.com/neverhood311/Stop-motion-OBJ/discussions) and we'll continue this conversation there.
