### ISSUE TITLE
How to extract a specific single frame from the imported mesh sequence?

### ISSUE THREAD

**Issue by linjiangya** [neverhood311/Stop-motion-OBJ#192]
**Is your feature request related to a problem? Please describe.**
Thank s for the amazing addon! I successfully made a video with your addon. Howver, I am now trying to visualize a motion sequence in a static figure. For that, I would like to extract several keyframes from the motion sequence and put them in the scene.

**Describe the solution you'd like**

**Describe alternatives you've considered**
1) I understand that I can just simply import the single .obj one by one, but it's just because I would manually move the motion sequence. The newly imported single obj mesh would not align with the mesh sequence I already moved.
2) Copy-and-paste the motion sequence will produce another motion sequence with exactly the same animation, but I want the copied one to be static at specific frame without animation.

Thank you for your help and your great work again!

**Comment by neverhood311** [comment]
If I understand correctly, you've imported a mesh sequence and you've translated/rotated/scaled it. Maybe you've also animated the translation/rotation/scale. You want to extract a few frames from the sequence, but you want them to have the same translation/rotation/scale and potentially the same animation. Am I understanding properly?

If this is correct, I'd suggest you make this change, if possible. Load your mesh sequence like normal, then create a new Empty object. Make your mesh sequence a child of the Empty object. Next, manually import the handful of keyframes and make those children of the Empty object. Now you can do your translation/rotation/scaling, but do it to the Empty parent object and not to the mesh sequence. That way, it will apply to both the mesh sequence and your manually-imported keyframes.

**Comment by linjiangya** [comment]
Yes, that's exactly what I was trying to do! :) Thank you for your prompt reply. You saved my day.
