### ISSUE TITLE
feature request stop-motion-stl

### ISSUE THREAD

**Issue by musmo** [neverhood311/Stop-motion-OBJ#2]
Would it be possible to have this also work for stl sequences? Thanks!

**Comment by neverhood311** [comment]
Thanks for the suggestion, though I can't promise I'll be able to get around to it anytime soon. Just so I'm aware, is it common to have animation software export sequences of .stl files, but not .obj files?

**Comment by musmo** [comment]
Hi Justin. I would say for more scientific applications yes. For example, currently, I'm trying to use paraview to export vtk files so that I can use them in Blender but the only option is to export to stl :-1:

**Comment by neverhood311** [comment]
I've got some time today. Lemme see what I can do.

**Comment by neverhood311** [comment]
I added the branch "stl-ply" that supports STL files (and PLY files, while I was at it). Go ahead and try it out. I'm gonna merge it into the master branch at the end of the day unless we find anything horribly wrong with it.

**Comment by musmo** [comment]
I have been trying to get this to work, but I don't see anything:
link to stls: https://www.dropbox.com/sh/m45qf0jg32skkf8/AAAmJcHZoRtzQ-VhZhYBLRaMa?dl=0

**Comment by neverhood311** [comment]
It looks like all of your .stl files are empty.
(as a side note, since the file numbers aren't zero-padded, they'll load in a weird order)

**Comment by musmo** [comment]
Ah of course, fixed that and the filename issue. Currently loading (taking a while, I should have probably tested a smaller case, but let's see how this goes...).

**Comment by musmo** [comment]
Cool it works for a small sequence!! Here's the problem though. For large sequences I think it crashes due to memory ...

**Comment by neverhood311** [comment]
Any chance you could share a large one with me so I can see up close?
Also, what's "large" and what's "small"?

**Comment by musmo** [comment]
Of course:
https://www.dropbox.com/sh/m45qf0jg32skkf8/AAAmJcHZoRtzQ-VhZhYBLRaMa?dl=0

The original sequence with almost 900 steps crashes my blender due to memory (12GB)

**Comment by neverhood311** [comment]
Thanks for the sample meshes. (I'm done with them, so you can free up your Dropbox space whenever you want)

Yeah, 8GB would probably do it! I'm not sure why, but Blender seems to inflate the file size of imported geometry. Your "short" sequence takes up about 139MB, but when I import it to Blender, the resulting .blend file is 183MB. To make it worse, Blender uses 833MB of memory with the sequence open. I might have a way to get memory usage down, but I don't think I can get the add-on to work without holding all of the meshes in memory.

I'm closing this issue, but I'll see about lowering memory usage.

**Comment by musmo** [comment]
No worries. Thanks for the added feature!  I guess  now you have to rename the rep  :P

**Comment by neverhood311** [comment]
Yeah, I just might have to change the name. I'm glad I could help.
I'm gonna merge the branch soon. You should snag the latest version once I do; I made a quick change that cuts memory usage nearly in half.

**Comment by musmo** [comment]
Great.  Also do mind telling me how I can specify the fps of the sequence that I import?

**Comment by neverhood311** [comment]
FPS is left to Blender. The addon will load every frame, but Blender's Frame Rate setting will control the playback speed. See the attached screenshot for how to change it:
![render_settings_fps](https://cloud.githubusercontent.com/assets/4615170/16350034/6d4e34de-3a19-11e6-9d74-197f1b5e37a6.png)

Is this what you're looking for?

**Comment by neverhood311** [comment]
@musm Do you happen to use Stop Motion OBJ still? I'm working on a new version which includes a feature that might solve the "too large to fit in memory" problem.

**Comment by musm** [comment]
Hi @neverhood311 it's actually been a while since I've used Stop Motion OBJ
