### ISSUE TITLE
Error message when selecting stop motion OBJ script on Blender

### ISSUE THREAD

**Issue by SimronThapa** [neverhood311/Stop-motion-OBJ#21]
There is a syntax error in File: "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\stop_motion_obj.py" line 99

dirPath: bpy:props.StringProperty(

SyntaxError: invalid syntax

**Comment by neverhood311** [comment]
Hi Simron,

Which version of Blender are you using? And which version of the Stop Motion OBJ did you try to install?

**Comment by neverhood311** [comment]
Closed since OP hasn't provided more info.
