### ISSUE TITLE
How can I export the dynamic model as an fbx file?

### ISSUE THREAD

**Issue by zhaobingshuai** [neverhood311/Stop-motion-OBJ#22]
Hi, I am very happy to find your plugin. This is a very useful tool. I have successfully implemented the animation. How can I export the dynamic model as an fbx file? I am going to view this model in Hololens and look forward to your answers, thank you very much.

**Comment by neverhood311** [comment]
Hello,

Thanks for reaching out. FBX and Alembic export has been on my to-do list for a while. I've experimented with it a bit, but without success. I'll keep trying as I find time, but I don't have a lot of spare time to dedicate to this addon.

**Comment by zhaobingshuai** [comment]
I think if this plugin can't export the animation as an .fbx file, then its meaning will be limited. I am looking forward to your further work and I am confident that your efforts will make this plugin even more valuable.

**Comment by jhz07** [comment]
> I think if this plugin can't export the animation as an .fbx file, then its meaning will be limited. I am looking forward to your further work and I am confident that your efforts will make this plugin even more valuable.

It'd be great to have this functionality in this plug-in. 
@zhaobingshuai  Could you find any solution to export as an fbx animation?

**Comment by neverhood311** [comment]
@zhaobingshuai @jhz07 I did some digging a while back. I'm not sure where I posted my findings, but I'll post them here again.
There's a problem with Blender's .FBX exporter which only allows linear interpolation of keyframes. In order for exports from Stop Motion OBJ to work, it would need constant interpolation (AKA no interpolation). I'm going to file a bug with Blender and see what they say. If it's not very high priority for them, I might look into fixing Blender myself. But no promises; unfortunately, this addon is pretty low on my priority list.

**Comment by jhz07** [comment]
Thank you @neverhood311 and look forward to your future work.

**Comment by zhaobingshuai** [comment]
Sorry，I can't find solution about it. I have given up.

赵丙帅     Bingshuai Zhao
Tel:(+86) 17634993409
Email: bingshuaizhao@outlook.com
________________________________
发件人: jhz07 <notifications@github.com>
发送时间: 2019年12月7日 下午 5:59
收件人: neverhood311/Stop-motion-OBJ <Stop-motion-OBJ@noreply.github.com>
抄送: Bingshuai Zhao <bingshuaizhao@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [neverhood311/Stop-motion-OBJ] How can I export the dynamic model as an fbx file? (#22)


I think if this plugin can't export the animation as an .fbx file, then its meaning will be limited. I am looking forward to your further work and I am confident that your efforts will make this plugin even more valuable.

It'd be great to have this functionality in this plug-in.
@zhaobingshuai<https://github.com/zhaobingshuai> Could you find any solution to export as an fbx animation?

―

**Comment by andredavidbrown** [comment]
Any solution to this?
I have the same need
Thanks

**Comment by neverhood311** [comment]
@andredavidbrown Unless the Blender developers re-write the FBX exporter to support multiple interpolation modes, I don't plan on supporting FBX export.

If there's any way you can use Alembic instead of FBX, a few users have had some success with that file format.
