### ISSUE TITLE
Converting sequence of .ply files into free view point video

### ISSUE THREAD

**Issue by nikhilkoditala** [neverhood311/Stop-motion-OBJ#23]
I am a kind of new to blender or 3d processing in general. Please bear with me. I have a sequence of .ply files which I need to convert to free view point video. I came across this repo and tried to follow the steps. I installed the addon and loaded the ply sequence. I am stuck here, as I don't know how to convert this mesh sequence into 360 degrees video. Any suggestions are appreciated.

Thanks,
Nikhil

**Comment by neverhood311** [comment]
Hi Nikhil,

Thanks for trying my addon and welcome to the Blender community!

Your question is outside the scope of this addon, but these links might help you figure out how to do 360 degree renders in Blender:

- YouTube: [Tutorial: How to Make a 360 video in Blender (In under 5 minutes)](https://www.youtube.com/watch?v=EscAx7uQMuU)
- Stack Exchange: [How can I create 360° Videos?](https://blender.stackexchange.com/questions/48163/how-can-i-create-360-videos)

In general, your best bet is to start with a simple Google search. If that doesn't turn up anything helpful, maybe try asking a question on [blender.stackexchange.com](blender.stackexchange.com) or [blenderartists.org](https://blenderartists.org)

Good luck!

**Comment by nikhilkoditala** [comment]
I think I was not able to communicate it to you correctly. I don't want to generate a 360 degree video of a single static frame. I have a sequence of point cloud frames similar to horse_obj_sequence. Now, I want to download sequence as animation (I was able to play it in blender but I dont know how to download them as it is in 360 degrees). I tried to google but couldn't find anything useful.

Please feel free to close this issue, if you still find it irrelevant..

Thanks,
Nikhil

**Comment by neverhood311** [comment]
When you say "free view point video", do you mean a video where you can move the camera around? Like the technique described by [this research (High-quality streamable free-viewpoint video)](http://hhoppe.com/proj/fvv/)? If so, I'm not entirely sure how you could do this in Blender.

A potential solution is to convert your point cloud sequence to an FBX animation or Alembic sequence, then import it into a game engine like Unity. I'm not sure if that is compatible with your workflow, though. And Stop Motion OBJ doesn't support exporting to FBX or Alembic (yet. I'm working on it).

Still, I think this might be a better question for Blenderartists.org.

Good luck

**Comment by nikhilkoditala** [comment]
> [this research (High-quality streamable free-viewpoint video)](http://hhoppe.com/proj/fvv/)

Yes I mean according to this research. I will try to look into the technique you mentioned. 
Thank you so much for your suggestions.

**Comment by gavan1** [comment]
@nikhilkoditala did you find a good solution to take the sequenced ply into Blender? Or was there a better format for working with streamed pointcloud or RGBD video into Blender?
