### ISSUE TITLE
"No matching files found..." Issue

### ISSUE THREAD

**Issue by drinner** [neverhood311/Stop-motion-OBJ#24]
Hello, 

  I have downloaded and installed the Stop Motion OBJ addon, and I have been able to access the addon and begin the process of importing OBJ Sequences into Blender.  However, during the file selection process, once I reach the point in you "Read me" file where you say: 

"n the File Name box, enter a common prefix of the files.
ex: If you have frame001, frame002, frame003, you could enter ‘frame’, 'fram', or even 'f'"

...I things fall apart.  For my OBJ sequence, the prefix for all the obj files in the folder is "Oil," so that's what I enter for the "common prefix".  Then, when I click on the "Load Mesh Sequence" button, I get a message that says: 

"No matching files found, make sure the root folder, file name, and file format are correct"

  ... The problem is, I KNOW these are all correct.  So now I am not sure what to do, at all.  Can you offer me any help?  

Thanks,
-Evan

I've included screenshots of both the file directory and the "prefix" settings in the "sequence/object tab.  
<img width="1150" alt="Screen Shot 2019-08-30 at 12 32 45 PM" src="https://user-images.githubusercontent.com/54718333/64040420-9a537c80-cb22-11e9-914b-8c33ba26325b.png">
<img width="448" alt="Screen Shot 2019-08-30 at 12 33 01 PM" src="https://user-images.githubusercontent.com/54718333/64040421-9a537c80-cb22-11e9-8992-04f5177407cd.png">

**Comment by neverhood311** [comment]
Hi drinner,

From what you've described, it appears as though nothing is wrong on your end. Would it be possible to send me two or three of the .OBJs from your sequence so I can try to debug from my end?

Kinda shooting in the dark here, but the only thing that maybe might be a problem is the length of your folder paths. Could you try the same sequence with a shorter folder path? Like C:/sequence/Oil obj sequence0001.obj?

Also, are these files on a network drive or on a local drive?

**Comment by StephenMcAvoy** [comment]
Hi, I was looking through the fault reports before I send in my own and came across this one. I had something similar when I moved the Mesh Sequence tab towards the top of Object properties and saved it in the Startup file. The console error is below. 
I resolved the issue by restoring the config and Scripts folders to a previous version.
The location in Win7 is:
%username%\AppData\Roaming\Blender Foundation\Blender\2.80

The console o/p is:

Read prefs: C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.80\python register_class(...):
Warning: 'OBJ_SEQUENCE_properties' doesn't contain '_PT_' with prefix & suffix
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\stop_motion_obj.py", line 509, in initSequenceController
    MSC = MeshSequenceController()
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\stop_motion_obj.py", line 156, in __init__
    self.loadSequenceFromData(obj)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\stop_motion_obj.py", line 256, in loadSequenceFromData
    bpy.data.meshes[t_meshName].inMeshSequence = True
KeyError: 'bpy_prop_collection[key]: key "" not found'
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\2.80\scripts
\addons\stop_motion_obj.py", line 545, in execute
    num = MSC.loadSequenceFromFile(obj, dirPath, fileName)
AttributeError: 'NoneType' object has no attribute 'loadSequenceFromFile'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by drinner** [comment]
Thanks, everyone.

  I'm sorry that I haven't been able to respond to this until now.  I can send you a few obj's from the beginning of the sequence.  How would you like to receive them, would that be through gmail?  Also, I will try changing the file path to something smaller to see how that works.  Thank you for your suggestions.

**Comment by neverhood311** [comment]
@drinner If you put them into a .zip file, you can attach it directly to this issue. Just make a new comment, and drag and drop your file into the text box.

I haven't been able to reproduce the issue yet. I've tried loading from a network drive and putting spaces in the filenames, but it still worked. I haven't yet tried spaces in folder names or really long paths. I'll try that out today, but I'd appreciate it if you tried my previous suggestions as well.

Also, which operating system are you using?

**Comment by drinner** [comment]
sure, I can do that, thanks!

**Comment by drinner** [comment]
Sure, here you go:

[obj sequence for Justin .zip](https://github.com/neverhood311/Stop-motion-OBJ/files/3574937/obj.sequence.for.Justin.zip)

**Comment by neverhood311** [comment]
Based on the presence of a __MACOSX folder inside that .zip you sent, I'm gonna guess that you're running Blender on OSX. Is that true? If so, there might be some funny stuff going on with the different file path conventions between OS's. Unfortunately, I don't have access to a Mac, so I'm unable to test it on one.
Have you gotten any OBJ sequence to load properly?

**Comment by neverhood311** [comment]
Closed due to inactivity
