### ISSUE TITLE
Materials disappearing when importing complex OBJs

### ISSUE THREAD

**Issue by StephenMcAvoy** [neverhood311/Stop-motion-OBJ#25]
Blender version: 2.80 (sub 75), branch: master, commit date: 2019-07-29 14:47, hash: f6cb5f54494e, type: 
build date: 2019-07-29, 09:44 AM

Add Mesh: Stop motion OBJ 2.0.0

By complex OBJ I mean an OBJ with multiple OBJs nested inside. 
E.G. a Poser model with hair and clothes. 

When Material per Frame is not ticked. The addon imports the OBJ correctly but when I move to the next frame all but one material is lost in all frames. 
When Material per Frame is ticked. The addon imports the OBJ correctly but each frame has its own material. As it should but makes editing a material across the animation, off-putting. :)

If I separate the meshes in Poser to have three simple OBJs. I can place the “sequence” containers in one “empty” and use it as I want. Below is an example video. (Partial nudity warning.)
https://youtu.be/fAoAl_cb3L8

I can supply a couple of OBJs from the series if required.

Now the praise which normally comes before the problem. :)
I can see me using this addon a lot. I have lots of BVH motion files that I have exported as meshes from Poser and rendered in Pov-Ray. But I have moved over to Blender completely now and importing a mesh sequence was missing. Thank you 
I might have one or two cosmetic suggestions.

Stephen

**Comment by neverhood311** [comment]
Thanks for the bug report. I've verified it in v2.0.0. If you could somehow send two or three OBJs of your sequence, that would be helpful for debugging.

As for cosmetic suggestions, I'd love to hear them. I'm always looking for ways to improve. Just be sure to add them as separate issues and I'll tag them as feature enhancements.

**Comment by StephenMcAvoy** [comment]
I zipped the required files including the images. One of them is a TIF :(
It is about 6 Meg so I will upload it here.

[Combined.zip](https://github.com/neverhood311/Stop-motion-OBJ/files/3573083/Combined.zip)

**Comment by neverhood311** [comment]
I've got a fix for this. You can find it at [https://github.com/neverhood311/Stop-motion-OBJ/tree/bug/materials-disappear](https://github.com/neverhood311/Stop-motion-OBJ/tree/bug/materials-disappear). Do you mind giving it a try?

**Comment by StephenMcAvoy** [comment]
Sorry, I think I answered elsewhere. 
:+1: 
That seems to have fixed it and so quick too. Well done.
Do you want to close the ticket or I will after a longer test?

**Comment by neverhood311** [comment]
If you're ok using this branch for a while, I'm gonna do some more extensive testing before I close it. I'm leaving on vacation for a week, so it may be a while before this gets merged in. Just want to make sure I didn't break anything else.

**Comment by StephenMcAvoy** [comment]
I am happy to use the updated addon. I imported a 250 frame animation yesterday. 
Enjoy your holiday. :)

**Comment by neverhood311** [comment]
Fixed in #29 
Sorry this took a while to merge. It's a long story, but I finally have approval from my company to continue contributing to this addon.

**Comment by StephenMcAvoy** [comment]
Thanks, I checked this with a  series of 250 frame OBJs with 3 OBJs per frame. Worked well.
