### ISSUE TITLE
Addon doesn't properly install from .zip file

### ISSUE THREAD

**Issue by carmandale** [neverhood311/Stop-motion-OBJ#30]
I download the plugin to add to 2.8 and after adding, nothing shows up. If I just open the python script and run it, the new mesh sequence menu item shows up, but I get this error:

Traceback (most recent call last):
  File "/stop_motion_obj.py", line 528, in execute
AttributeError: 'NoneType' object has no attribute 'newMeshSequence'

any help or ideas?

**Comment by StephenMcAvoy** [comment]
I had problems installing the addon using the preferred method. I ended up taking the “stop_motion_obj.py” file out of its folder/zip file and putting it in 
%AppData%\Blender Foundation\Blender\2.80\scripts\addons
Restarted Blender and it worked.
As for the other problem. I got something similar when I moved the sequence tab higher in the screen order and saved that as the Blender new file default. That has not been confirmed as a bug.

Stephen

**Comment by neverhood311** [comment]
@carmandale Did you restart Blender after installing the addon?

**Comment by carmandale** [comment]
I did restart blender. Could it have anything to do with being on Mac? I’ll try it on my PC later. 




Dale Carman | Executive Creative Director
Groove Jones | 3900 Willow St., Dallas TX 75226
214-674-0616 | www.GrooveJones.com

**Comment by neverhood311** [comment]
@carmandale Problems on Mac are definitely possible; I don't have access to a Mac, so there's been little or no testing there.

When you say "and after adding, nothing shows up", what specifically do you mean by "adding" and "nothing shows up"? What are the exact steps you took and what did you expect to see?

**Comment by carmandale** [comment]
I go to edit/preferences. Under Add-ons, click install. Select Stop-motion-OBJ-2.0.0.zip. click Install Add-on.

This returns…

Modules Installed () from '/Users/dalecarman/Downloads/Stop-motion-OBJ-2.0.0.zip' into '/Users/dalecarman/Library/Application Support/Blender/2.80/scripts/addons'

Nothing shows up to enable for the add-on.

If I filter by “obj” I see:


I restart, and nothing is under the add/mesh menu.

I check /Users/dalecarman/Library/Application Support/Blender/2.80/scripts/addons and the folder is there, but nothing shows up to enable under the add-ons.

Thanks,
Dale



  <http://www.groovejones.com/>
Dale Carman <mailto:dale@groovejones.com> | Executive Creative Director
Groove Jones <http://www.groovejones.com/> | 3900 Willow St., Dallas TX 75226 <https://www.google.com/maps/place/3900+Willow+St,+Dallas,+TX+75226/@32.7854205,-96.7710561,17z/data=!3m1!4b1!4m2!3m1!1s0x864e98c077063b57:0x2403d0942b293de2?hl=en> 					 			
214-674-0616 | <tel:+1-214-674-0616> www.GrooveJones.com <http://www.groovejones.com/>

**Comment by neverhood311** [comment]
Try unzipping the Stop-motion-OBJ-2.0.0.zip file and copying `stop_motion_obj.py` directly into your `/Users/dalecarman/Library/Application Support/Blender/2.80/scripts/addons` folder. Then restart Blender and see if it shows up in your addons list to enable.

**Comment by carmandale** [comment]
Justin,
That worked and made the add-on show up. But I get this error when I go to add/mesh sequence



Any ideas?

Thanks,
Dale



  <http://www.groovejones.com/>
Dale Carman <mailto:dale@groovejones.com> | Executive Creative Director
Groove Jones <http://www.groovejones.com/> | 3900 Willow St., Dallas TX 75226 <https://www.google.com/maps/place/3900+Willow+St,+Dallas,+TX+75226/@32.7854205,-96.7710561,17z/data=!3m1!4b1!4m2!3m1!1s0x864e98c077063b57:0x2403d0942b293de2?hl=en> 					 			
214-674-0616 | <tel:+1-214-674-0616> www.GrooveJones.com <http://www.groovejones.com/>

**Comment by carmandale** [comment]
Justin, do you forsee any issue with an 1800 frame .ply sequence?

**Comment by neverhood311** [comment]
It completely depends on the combined size of the .ply files. The addon loads every frame into memory, so if you have lots of RAM, 1800 might be ok. But it would sure take a long time to import. If the full sequence doesn't fit in memory, you might try splitting it into smaller chunks and creating a different .blend file for each subset. I haven't personally tried this workflow, so I don't know how annoying it might be, but it's a last resort.

**Comment by codylukas** [comment]
I have downloaded the 2.0 version, unzipped it and copied it directly into the C:/Program File/Blender Foundation/Blender/2.97/scripts/addons and this is the error message i receive when i try to install it in user preferences.

![Uploading 83105015_120075612605843_6225655743815614464_n.jpg…]()

**Comment by neverhood311** [comment]
If you're trying to install the addon for Blender 2.79, you'll want to download and install [v1.1.1](https://github.com/neverhood311/Stop-motion-OBJ/releases/tag/0.2.79.2). Keep in mind that this version is no longer supported. (See the README, near the top). The latest version is incompatible with Blender 2.79, which is why you're getting this error.

If you decide to upgrade to Blender 2.81, then you can use [v2.0.2](https://github.com/neverhood311/Stop-motion-OBJ/releases/tag/v2.0.2). To install this version, download the code as a .zip file, then install it using the [updated installation instructions](https://github.com/neverhood311/stop-motion-obj#installing-stop-motion-obj) in the README

**Comment by codylukas** [comment]
worked perfectly. thank you
