### ISSUE TITLE
Is export to Alembic possible with this?

### ISSUE THREAD

**Issue by flowb** [neverhood311/Stop-motion-OBJ#31]
Hi,

Title says it all. Can I use this to load a sequence of .PLY files and then export said sequence to Alembic?

Thanks!

**Comment by neverhood311** [comment]
Unfortunately, no. There are some technical roadblocks within Blender itself that prevent exporting mesh sequences to Alembic. Also unfortunately, I have no idea when those roadblocks might be removed. I will let you know if/when it becomes possible.

**Comment by flowb** [comment]
Hi,

Thanks for the quick reply!

I guess I'll start diving into this as well. :)
