### ISSUE TITLE
Blender-style installation issues

### ISSUE THREAD

**Issue by andres-a-salas** [neverhood311/Stop-motion-OBJ#34]
Hi neverhood,

First off, thanks a ton for your development efforts, this is regularly maintained and extremely helpful!

On to the issue:

Using the new Blender-style installation on the zip file went well except for a minor hiccup:

The default name that came from the download (Stop-motion-OBJ-2.0.2) doesn't seem to be recognized by Blender when present in the Addons folder. I renamed it to stop_motion and everything went smoothly.

Versions:
Blender  2.81
Stop-motion-OBJ   2.0.2

All the best,
Andres

**Comment by neverhood311** [comment]
Hi Andres, see Issue #35. I think I've got a solution. Thanks for the tip.

**Comment by andres-a-salas** [comment]
A drop in the ocean compared to how helpful this is!

All the best,
Andres
