### ISSUE TITLE
Can't install addon in blender 2.81

### ISSUE THREAD

**Issue by damnMeddlingKid** [neverhood311/Stop-motion-OBJ#35]
I've tried following the installation steps for the 2.0.2 release in blender 2.8.1 but i dont see the addon in the list of addons after installation.

installation steps i've followed:

1) Downloaded zip file from https://github.com/neverhood311/Stop-motion-OBJ/releases/tag/v2.0.2
2) Edit > preferences > addons > install , selected file from step 1
3) Blender says it has installed the addon, no errors
4) type "obj" in addon search and can't find the addon

I also tried restarting blender and followed the usage steps but i dont have the option in the add mesh menu.

**Comment by michaelzhou0723** [comment]
I experienced the same just now

**Comment by neverhood311** [comment]
I think this comes down to naming conventions that Blender is expecting (and I wasn't familiar with). I've updated the latest release with the correct naming. You'll have to go to [the latest release](https://github.com/neverhood311/Stop-motion-OBJ/releases/tag/v2.0.2) and download the file called Stop-motion-OBJ-2.0.2.zip. Don't download the "Source code (zip)" file.

Also, if you've already tried to install the addon with a previous or broken version, you might have to clear out the old one first. In Windows, go to `%appdata%/Roaming/Blender Foundation/Blender/2.81/scripts/addons` and delete any existing `Stop-motion-OBJ` folders. In Mac or Linux, the process will probably be similar, but you'll have to figure out where Blender is copying these folders to first.

Sorry about this!

Lemme know if this process works for either of you.

**Comment by damnMeddlingKid** [comment]
that worked great. thanks for awesome addon!
