### ISSUE TITLE
wrong frames number import

### ISSUE THREAD

**Issue by ialebedev** [neverhood311/Stop-motion-OBJ#4]
I have the obj sequence of OBJs with water simulation from Houdini.
I tried to import it. All was imported well, but the frame numbers are wrong. Looks like frames are randomly sorted. I've baked the sequence and found out that the keys are wrong.

For example, in frame 1 I have keys animated on o_Wave_008, in frame 2 on o_Wave_008 ans so on.
Why that happened, I don't know. But it is 100% bug.

**Comment by neverhood311** [comment]
Would it be possible to send me a few of your OBJs so I can take a look?

**Comment by ialebedev** [comment]
Sure
Here it is https://cloud.mail.ru/public/qUGL/TYeqpzy1F

**Comment by ialebedev** [comment]
If you can fix it in short time it would be amazing because for now it looks like the only solution ))
I am creating cg for commercial and I want to render it in blender. So I need to import the simulation to blender.

**Comment by neverhood311** [comment]
For some reason, your link isn't loading. Do you have Dropbox? Or some other way to get me the files?

**Comment by ialebedev** [comment]
https://www.dropbox.com/s/sm7nsqghw5wr9nl/Wave.zip?dl=0

**Comment by neverhood311** [comment]
This sequence loaded just fine for me in Windows. What operating system are you running?

**Comment by ialebedev** [comment]
Debian Linux 64bit

**Comment by neverhood311** [comment]
There's a possibility that Windows and Linux read the files in a different order from each other. Lemme make a little change to the script and I'll have you see if it fixes the issue.

**Comment by neverhood311** [comment]
Ok, I made the 'sorted_files' branch. It didn't seem to break anything, so let's hope it fixes the issue you're having. Go ahead and try it out and let me know if it works.
https://github.com/neverhood311/Stop-motion-OBJ/tree/sorted_files

**Comment by ialebedev** [comment]
You did it, man!!! Thanks a lot!

**Comment by neverhood311** [comment]
Great! Glad I could help. Good luck with your project.

**Comment by ialebedev** [comment]
Thank a lot!
