### ISSUE TITLE
Baking the sequence while in Edit Mode causes an error

### ISSUE THREAD

**Issue by freder** [neverhood311/Stop-motion-OBJ#40]
hi, I just tried to bake a sequence and got the following error:

![image](https://user-images.githubusercontent.com/724844/76170839-0d027c00-6186-11ea-9891-3b7f6331db9f.png)

- blender 2.82.7
- plugin 2.0.2

**Comment by freder** [comment]
wait, I figured it out — I was in edit mode.

**Comment by neverhood311** [comment]
Yep, that'll do it.
However, I should probably be detecting this and warning the user instead of causing an error.

**Comment by neverhood311** [comment]
Fixed in #48
