### ISSUE TITLE
How to export mesh sequence to Alembic?

### ISSUE THREAD

**Issue by vertstream** [neverhood311/Stop-motion-OBJ#46]
Sorry if you have documentated this elsewhere but I am a studying 3d and found your addon. It’s been great as has allowed me to import the .ply files into blender perfectly. I now like to convert them to alembic files To do some more work in Houdini. If I export them from blender as alembic files I only get the first frame or whatever one I make the first frame of the export Same with fbx. Any idea how I can get the other frames/meshes out In an export. Much appreciated.

**Comment by neverhood311** [comment]
Hi vertstream. A quick disclaimer: FBX and Alembic exports are not officially supported by Stop Motion OBJ.

That being said, some users have figured out a way to export to Alembic in specific cases. There's a conversation about it in the Stop Motion OBJ [blenderartists thread](https://blenderartists.org/t/stop-motion-obj-obj-stl-ply-sequence-importer/670105/87). Basically, you import your sequence, don't bake it, apply a modifier to the sequence (preferrably one that doesn't actually change the mesh), then export an Alembic file.

Give that a try and see if it works for you.

**Comment by neverhood311** [comment]
@vertstream Did you get a chance to try this workaround?

**Comment by vertstream** [comment]
Yes thanks Justin that did work. Much appreciated 👍
