### ISSUE TITLE
[req] plz have a look at multithreading the import.

### ISSUE THREAD

**Issue by NicTanghe** [neverhood311/Stop-motion-OBJ#51]
hello so large sequences seem to take a verry long time import.
i norices that only 1 thread was being used tho and that the imports show up in order on the console. so i was wondering if it was at all possible to multithread this ?

just seems like adding an async to a for loop somewhere.

**Comment by neverhood311** [comment]
@NicTanghe Thanks for the feedback. My brief tests (first using the `multiprocessing` library, then with the `asyncio` library) didn't seem to be very straightforward. Regardless, I think this is still worth looking into. I put it on my backlog.
In the meantime, let's hope someone writes a faster OBJ importer so we don't even need this.

**Comment by NicTanghe** [comment]
thx dude that's awsome. i hope i get thee rest working.

**Comment by neverhood311** [comment]
My tests were unsuccessful. Closing
