### ISSUE TITLE
Crash on alfa 3 i htink only when i enable vieuwport shading and do something.

### ISSUE THREAD

**Issue by NicTanghe** [neverhood311/Stop-motion-OBJ#53]
**System Information**
Operating system:

**Addon version**
Broken: (example: 3.0.9 ?)
Worked: (no idea)

**Describe the bug**
blender crashes

**Steps To Reproduce**
enable vieuwport rendering.
do a few things
**Expected behavior**
it should work

**console**

Traceback (most recent call last):
  File "/root/.config/blender/2.82/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 500, in initSequenceController
    MSC = MeshSequenceController()
  File "/root/.config/blender/2.82/scripts/addons/Stop-motion-OBJ/stop_motion_obj.py", line 142, in __init__
    self.loadSequenceFromData(obj)
  File "/root/.config/blender/2.82/scripts/addons/io_scene_usdz/__init__.py:141
    assign as a type annotation: EXPORT_OT_usdz.exportMaterials
    assign as a type annotation: EXPORT_OT_usdz.exportAnimations
    assign as a type annotation: EXPORT_OT_usdz.bakeTextures
    assign as a type annotation: EXPORT_OT_usdz.bakeAO
    assign as a type annotation: EXPORT_OT_usdz.bakeAOSamples
    assign as a type annotation: EXPORT_OT_usdz.bakeTextureSize
    assign as a type annotation: EXPORT_OT_usdz.globalScale
    assign as a type annotation: EXPORT_OT_usdz.useConverter
0  meshes freed
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Read blend: /home/tanghe/Blender/mandelbulb.blend

not sure if actually related to your add-on.

**Comment by neverhood311** [comment]
Which version is this? The line `MSC = MeshSequenceController()` is found in version 2.0.2, but it's been removed in the version-3 branch. You're saying this happened in the alpha version though, right?

**Comment by NicTanghe** [comment]
hmm odd well i reinstalled my system with propretiery nvidia drivers this time i'l c if i'm still having issues after i re-setup everything.

**Comment by neverhood311** [comment]
@NicTanghe Were you able to sort out this issue?

**Comment by neverhood311** [comment]
Closed due to inactivity
