### ISSUE TITLE
Deleted mesh sequence remains in memory

### ISSUE THREAD

**Issue by TomatoAddict2** [neverhood311/Stop-motion-OBJ#54]
**System Information**
Operating system:
Windows 10 64-bit
Blender 2.82

**Addon version**
Broken: 2.0.2

**Describe the bug**
After creating a mesh sequence, loading PLY files, and then deleting the mesh sequence, the blender project still occupies as many bytes as before deleting.

**Steps To Reproduce**
1. Create new project in Blender
2. Add mesh sequence
3. Load a series of PLY files into the sequence (I haven't checked with OBJ or STL files)
4. Save blender project
5. Note the size of the .blend file
6. Delete the mesh sequence object from blender project
7. Save project again
8. Note the size of the .blend file - it haven't dimished significantly
Optionally:
9. File -> Clean Up -> Purge all
10. Save project again
11. The .blend file is still too large
12. Create a new mesh sequence in the same project and load the same series of PLY files.
13. Save project
14. Now it is twice as large as in point 4, even though the old mesh sequence was deleted and new one was created with the same contents.

**Expected behavior**
8. After deleting the mesh sequence, the .blend file should be as small as before creating the mesh sequence, at least approximately.
11. Same as point 8
14. The .blend file should have approximately the same size as in point 4.

**Comment by neverhood311** [comment]
Yes, this annoying little bug has been around for a while.

This has to do with how Stop Motion OBJ ensures that all of the meshes in a sequence are saved in the .blend file. When you delete a sequence, all of the mesh data sticks around. However, each time you start up Blender and open a file, it checks for mesh data whose parent object has been deleted and frees all of it. The next time you save the .blend file, it should shrink to an expected size.

I'm not sure what's the best way to really fix this but hopefully this workaround is sufficient for now.

**Comment by neverhood311** [comment]
I'm currently working on the next version of the addon (version 2.1.0) and I've just added a new feature to address this issue. I couldn't figure out how to automatically clean up the extra data as soon as the sequence is deleted (there's no good way to tell when an object has been deleted). So I've added a dedicated Delete Sequence button to the mesh sequence settings. The latest alpha release includes this change. If you're brave, you're welcome to try it out. I'm hoping to do a final release within a month or two.

**Comment by neverhood311** [comment]
I just released a new alpha version (2.1.0.alpha.17) that does some in-depth cleanup of the mesh sequence. You have to use the dedicated `Delete Sequence` button, but it tries to delete all meshes, materials, and image textures referenced by the mesh sequence.

**Comment by TomatoAddict2** [comment]
I installed 2.1.0.alpha.17. I succesfully deleted the sequence created with version 2.0.2. This time file size shrunk as expected. However after installing the new plugin version, I can't add new sequence. I look in the menu Add->Mesh-> and the "Mesh Sequence" is missing

**Comment by neverhood311** [comment]
Glad to hear the file size shrunk as expected.

I forgot to mention that the new version had a major overhaul of the UI. To add a new sequence, now you have to do File > Import > Mesh Sequence. Check out the new [Quick Start tutorial](https://github.com/neverhood311/stop-motion-obj/wiki#quick-start) if you're stuck. And reach out to me if you're still stuck after reading through the tutorial.

**Comment by TomatoAddict2** [comment]
Works well. Thank you. 
P.S. The Streaming mode will be useful in my case too.
