### ISSUE TITLE
Import Mesh Sequence to start at frame other than the beginning of the animation.

### ISSUE THREAD

**Issue by StephenMcAvoy** [neverhood311/Stop-motion-OBJ#60]
**Is your feature request related to a problem? Please describe.**
Possibly*. See further down.

**Describe the solution you'd like**
I would like Stop-motion-OBJ to start the sequence at a named frame. The enhancement should have an additional Frame Mode for how Blender displays the frames before the sequence starts to be active. Similar options to what you have to the end of the sequence.

**Describe alternatives you've considered**
I imported a 45 frame sequence with the Frame Mode set to bounce. I set the visibility (Viewport and Rendering) of the sequence to be off for the first 45 frames, on for the next 45 frames then off for the remainder of the frames.
I imported the first OBJ file of the sequence with its visibility set to on until frame 46 when it is switched off for the rest of the frames.
I imported the last file of the sequence with its visibility set to off until frame 91 when it is switched on for the rest of the frames.
This gives a static model until frame 46 then the animation is visible until frame 91 then is static until the end of the animation.
Think of a statue coming to life, moving then being static in the new position.

*
Most of the times I have tried to create a video of the above scene. Blender has just crashed without any warning.

**Additional context**
Below is a video of what I expect. Nudity and bad UV mapping warning. Sorry about the UV mapping I’ve had problems since I upgraded Poser. 
https://youtu.be/LuhPw2XXjqw

**Comment by neverhood311** [comment]
Lemme see if I've understand this. You set the frame mode to Bounce, but you want to see frames 46-90, which should be playing in reverse. Is that correct?

Then you want the new "start" and "end" frames to extend?

**Comment by StephenMcAvoy** [comment]
Oh dear.  I did not read the documentation. <Blush> I see that you have anticipated me. The only other thing that might be useful is for the pre-start and post end to be allowed to be different.

**Comment by StephenMcAvoy** [comment]
Might as well close this now.
