### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by HoltHunter** [neverhood311/Stop-motion-OBJ#7]
I have installed the script on blender, but when I click on Add>Mesh>Mesh Sequence I get a script error. Here is what the logs say:

![capture](https://cloud.githubusercontent.com/assets/7268782/26690229/21bda790-46be-11e7-958c-cc6dda9a018e.PNG)

**Comment by neverhood311** [comment]
Hi HoltHunter,

Quick question: Did you restart Blender after you installed the addon?

**Comment by HoltHunter** [comment]
Oops. Yes that was it
