### ISSUE TITLE
v2.1.0.alpha.14:    Workaround for materials being kept in memory.

### ISSUE THREAD

**Issue by StephenMcAvoy** [neverhood311/Stop-motion-OBJ#76]
I've developed a workaround for materials being kept in memory. It is basically a test script. Once you are happy that it works there is no need to do the optional step. 

1.	Import Mesh Sequence
2.	Play sequence.
[Optional]
3.	Check that there are multiple materials for each group.
4.	Save file.
5.	Exit Blender.
6.	Start Blender.
7.	Load saved file
[Optional]
8.	Check that there is only one material for each group.

<OT>
Does anyone use Poser meshes? I’m having trouble with UV mapping on most Victoria 4 characters. 
Blender now only supports the advanced node-based shading model for its materials, most IO formats only support a basic shading model, similar to the legacy fixed pipeline of old GPUs
https://docs.blender.org/manual/en/latest/addons/import_export/node_shaders_info.html
Does anyone have any experience with this?
</OT>

**Comment by StephenMcAvoy** [comment]
Sorry about the lack of formatting.

**Comment by neverhood311** [comment]
Yesterday I pushed a new version (alpha.17) that does more in-depth cleanup. I basically comb through  the objects, materials, and image textures referenced by the mesh sequence. I then start deleting from the top-down. First objects, then materials, then image textures. I make sure not to delete anything that still has "users", meaning that something outside the mesh sequence is referencing it. This seems to work fairly well, at least with my test case.

I don't know of anyone specific that uses Poser models. Honestly, I don't see much of what anyone does with this add-on.
