### ISSUE TITLE
Could you add a feature to keep vertices?

### ISSUE THREAD

**Issue by j20232** [neverhood311/Stop-motion-OBJ#88]
## About

Current implementation may have a bug not to keep vertex indices when we load `.obj` meshes at Blender 2.83.0.

The bug is caused by not setting  `split_mode="OFF"` which is attributes of `bpy.ops.import_scene.obj`.
Reference: https://docs.blender.org/api/current/bpy.ops.import_scene.html#bpy.ops.import_scene.obj

In naive implementation, I can fix the bug as follows.

- https://github.com/neverhood311/Stop-motion-OBJ/blob/master/stop_motion_obj.py#L72

```py
def importFuncFromTypeNumber(_typeNumber):
    # OBJ
    if (_typeNumber == 0):
        return bpy.ops.import_scene.obj, {"split_mode": "OFF"}
    # STL
    elif (_typeNumber == 1):
        return bpy.ops.import_mesh.stl, {}
    # PLY
    elif (_typeNumber == 2):
        return bpy.ops.import_mesh.ply, {}
    return None
```

- https://github.com/neverhood311/Stop-motion-OBJ/blob/master/stop_motion_obj.py#L185

```py
importFunc, kwargs = importFuncFromTypeNumber(
            int(_obj.mesh_sequence_settings.fileFormat))
```

- https://github.com/neverhood311/Stop-motion-OBJ/blob/master/stop_motion_obj.py#L199

```py
importFunc(filepath=file, **kwargs)
```

Could you fix the bug?

**Comment by neverhood311** [comment]
Which version of Stop Motion OBJ are you using?

**Comment by j20232** [comment]
Thank you for your reply.
The version is 2.0.2.

**Comment by neverhood311** [comment]
I don't really consider that a bug, more of a feature request. In version 2.0.2 and earlier, I don't use any non-default import settings (as you've seen in the code).

However, all of that is changing in version 2.1. You'll be able to specify most of the built-in import settings for each file format as you're importing a mesh sequence. Version 2.1 is in the Beta phase so all of the new functionality is in place, I'm just working on finding and fixing bugs now. If you'd like to try out the Beta, feel free to grab it from the [releases](https://github.com/neverhood311/Stop-motion-OBJ/releases) page. And please report any bugs you find. (and take a look at the [project wiki](https://github.com/neverhood311/Stop-motion-OBJ/wiki); the way you import a mesh sequence has changed.)
