### ISSUE TITLE
.ply files over 100 are "glitching"

### ISSUE THREAD

**Issue by theplyman** [neverhood311/Stop-motion-OBJ#9]
So here's what's going on.
I have got everything to work smoothly when i label my .ply files "name001" to "name009" then i switch to "name10" to "name100", when i do this it all works and is awesome, really love this addon by the way, amazing work.
But when I go to "name101" or over it plays the .ply files that are over 100 in between the .ply files that are going from 1 to 100.
To fix this i have done "name0100" "name00100" and also padded from 1 to 100, i have even mixed and matched with and without the padding and nothing seems to work.
Any ideas on whats going on here?
Could use some help.
Also I am having trouble rendering the sequence in cycles render, how does one go about that?

**Comment by neverhood311** [comment]
Just to be clear, your file numbers look like "0001", "0015", "0123", "1009" etc.? So there is the same number of digits on the end of _**each and every**_ file?

If there are, in fact, the same number of digits on the end of every file, could you somehow send me a few of your files? Maybe frames 90 through 110?

**Comment by theplyman** [comment]
Wow I feel pretty dumb, thought you had to pad 00 at the beginning of each
file. I can't try this right now but will tonight for sure. Thanks so much
for the fast response. Sorry about posting on the github page, couldn't
find your email. Kinda new to github.
Also, I'm still having trouble getting the sequence to render in cycles.
How do I get it to render in cycles?

**Comment by neverhood311** [comment]
No sweat. Glad it's working out. This is the exact place I want people posting questions and bugs. Not crazy about handing my email out.

When rendering these sequences with Cycles, you should be able to treat them like any other object. Just select the object, apply a shader, and hit render.
UVs will be kinda tricky since you have to unwrap each file individually (if that hasn't been done for you already), but I don't know if you need UVs for your project.

**Comment by theplyman** [comment]
So i am still having some problems with getting it to render, i put a
material on it  and it still doesn't render, which i am pretty sure
material is the same as a shader right?
I am going to send you a .ply file one of the many i am trying to upload
and render and you can tell me what you think.
The .ply does have RGB data on it but i have't found someone that can help
me get it into blender yet.

Thanks again for helping me out with this process!

**Comment by neverhood311** [comment]
Better yet, send me a .blend file with a few .ply frames in it and a material applied.

If you could temporarily share a Dropbox folder with me, that'd be easiest. Just post the link in this thread.

**Comment by theplyman** [comment]
so i shared it with notifications@github.com, is this right?

**Comment by neverhood311** [comment]
No, just make it public and post a link to it in this thread. I'll go copy the file to my computer, then I'll let you know so you can make the folder private if you want.

**Comment by theplyman** [comment]
https://www.dropbox.com/sh/md31vit9xeesmyg/AADpMNh2wR0GPX6i8qETOxfca?dl=0

**Comment by theplyman** [comment]
first time using dropbox, sorry it took so long, hope that works.

**Comment by neverhood311** [comment]
So it looks like your "meshes" are actually point clouds. You're going to have to figure out how to convert each frame to a mesh. That's beyond me, but I'm sure there are tutorials out there.

**Comment by theplyman** [comment]
Okay thanks for looking at it and helping me out, Much appreciated.
